/**
 * PDF Report HTML Template
 *
 * Generates a complete HTML document that Puppeteer renders to PDF.
 * Self-contained with inline CSS.
 */

interface ReportModel {
  name: string;
  overallScore: number;
  categoryScores: Record<string, number>;
  avgTokensPerSec: number;
  promptResults: Array<{
    promptText: string;
    response: string;
    score: number;
    category: string;
  }>;
}

interface ReportData {
  runId: string;
  suiteName: string;
  suiteType: string;
  startedAt: string;
  completedAt: string | null;
  models: ReportModel[];
  judgeModel: string | null;
  verdict: string;
  hardware?: { class?: string; gpu?: string; ram?: string };
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function scoreColor(score: number): string {
  if (score >= 80) return "#00FF66";
  if (score >= 60) return "#F59E0B";
  if (score >= 40) return "#F97316";
  return "#EF4444";
}

export function generateReportHTML(data: ReportData): string {
  const sortedModels = [...data.models].sort((a, b) => b.overallScore - a.overallScore);
  const winner = sortedModels[0];
  const dateStr = new Date(data.startedAt).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>ModelSweep Report - ${escapeHtml(data.suiteName)}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #000; color: #E4E4E7; font-size: 11px; line-height: 1.5;
  }
  .page { page-break-after: always; padding: 60px 50px; min-height: 100vh; }
  .page:last-child { page-break-after: auto; }

  /* Cover */
  .cover { display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; }
  .cover h1 { font-size: 32px; color: #00FF66; font-weight: 700; letter-spacing: -1px; }
  .cover .suite-name { font-size: 20px; color: #A1A1AA; margin-top: 12px; }
  .cover .meta { color: #71717A; font-size: 12px; margin-top: 40px; }
  .cover .verdict { color: #E4E4E7; font-size: 14px; margin-top: 30px; max-width: 500px; }
  .brand { color: #00FF66; font-family: monospace; font-size: 10px; letter-spacing: 3px; text-transform: uppercase; margin-bottom: 20px; }

  /* Summary */
  h2 { font-size: 16px; color: #00FF66; margin-bottom: 16px; border-bottom: 1px solid #27272A; padding-bottom: 8px; }
  h3 { font-size: 13px; color: #D4D4D8; margin-bottom: 8px; }
  .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin-bottom: 24px; }
  .summary-card {
    background: #0A0A0A; border: 1px solid #27272A; border-radius: 8px; padding: 16px;
  }
  .summary-card .label { color: #71717A; font-size: 10px; text-transform: uppercase; letter-spacing: 1px; }
  .summary-card .value { font-size: 24px; font-weight: 700; font-family: monospace; margin-top: 4px; }

  /* Table */
  table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
  th { background: #0A0A0A; color: #71717A; font-size: 10px; text-transform: uppercase; letter-spacing: 1px; text-align: left; padding: 8px 12px; border-bottom: 1px solid #27272A; }
  td { padding: 8px 12px; border-bottom: 1px solid #18181B; }
  tr:hover { background: rgba(0,255,102,0.02); }
  .score { font-family: monospace; font-weight: 700; }

  /* Details */
  .prompt-block { background: #0A0A0A; border: 1px solid #27272A; border-radius: 8px; padding: 12px; margin-bottom: 12px; }
  .prompt-text { color: #A1A1AA; font-size: 10px; margin-bottom: 8px; }
  .response-text { color: #D4D4D8; font-size: 10px; max-height: 100px; overflow: hidden; white-space: pre-wrap; }

  /* Footer */
  .footer { color: #3F3F46; font-size: 9px; text-align: center; margin-top: 40px; font-family: monospace; }
</style>
</head>
<body>

<!-- Cover Page -->
<div class="page cover">
  <div class="brand">MODELSWEEP</div>
  <h1>Evaluation Report</h1>
  <div class="suite-name">${escapeHtml(data.suiteName)}</div>
  <div class="meta">
    ${dateStr} &middot; ${data.models.length} model${data.models.length !== 1 ? "s" : ""} tested
    ${data.judgeModel ? ` &middot; Judge: ${escapeHtml(data.judgeModel)}` : ""}
  </div>
  <div class="verdict">${escapeHtml(data.verdict)}</div>
  <div class="footer">Generated by ModelSweep &middot; Run ID: ${data.runId}</div>
</div>

<!-- Executive Summary -->
<div class="page">
  <h2>Executive Summary</h2>
  <div class="summary-grid">
    ${sortedModels.map(m => `
    <div class="summary-card">
      <div class="label">${escapeHtml(m.name)}</div>
      <div class="value" style="color: ${scoreColor(m.overallScore)}">${m.overallScore}%</div>
    </div>
    `).join("")}
  </div>

  <h2>Results</h2>
  <table>
    <thead>
      <tr>
        <th>Model</th>
        <th>Overall</th>
        <th>Speed (tok/s)</th>
        ${Object.keys(winner?.categoryScores || {}).map(c => `<th>${escapeHtml(c)}</th>`).join("")}
      </tr>
    </thead>
    <tbody>
      ${sortedModels.map(m => `
      <tr>
        <td>${escapeHtml(m.name)}</td>
        <td class="score" style="color: ${scoreColor(m.overallScore)}">${m.overallScore}%</td>
        <td class="score">${m.avgTokensPerSec.toFixed(1)}</td>
        ${Object.values(m.categoryScores).map(s => `
          <td class="score" style="color: ${scoreColor(s)}">${s}%</td>
        `).join("")}
      </tr>
      `).join("")}
    </tbody>
  </table>

  <h2>Methodology</h2>
  <div style="color: #A1A1AA; margin-bottom: 24px;">
    <p><strong>Suite type:</strong> ${escapeHtml(data.suiteType)}</p>
    <p><strong>Scoring:</strong> Gate checks (empty, refusal, repetition, gibberish, truncation) ${data.judgeModel ? `+ LLM Judge (${escapeHtml(data.judgeModel)})` : ""}</p>
    ${data.hardware?.gpu ? `<p><strong>Hardware:</strong> ${escapeHtml(data.hardware.gpu)} / ${escapeHtml(data.hardware.ram || "")}</p>` : ""}
  </div>
</div>

<!-- Detailed Results -->
${sortedModels.map(m => `
<div class="page">
  <h2>${escapeHtml(m.name)} - Detailed Results</h2>
  <div class="summary-card" style="margin-bottom: 16px;">
    <div class="label">Overall Score</div>
    <div class="value" style="color: ${scoreColor(m.overallScore)}">${m.overallScore}%</div>
  </div>
  ${m.promptResults.slice(0, 10).map(pr => `
  <div class="prompt-block">
    <div class="prompt-text"><strong>[${escapeHtml(pr.category)}]</strong> ${escapeHtml(pr.promptText.slice(0, 200))}</div>
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 4px;">
      <span class="score" style="color: ${scoreColor(pr.score)}">${pr.score}%</span>
    </div>
    <div class="response-text">${escapeHtml(pr.response.slice(0, 500))}</div>
  </div>
  `).join("")}
</div>
`).join("")}

</body>
</html>`;
}
